### **Python program to multiply two matrices**

Method 1: Using Simple Nested Loops






In [1]:
# Program to multiply two matrices using nested loops 

# take a 3x3 matrix 
A = [[12, 7, 3], 
	[4, 5, 6], 
	[7, 8, 9]] 

# take a 3x4 matrix	 
B = [[5, 8, 1, 2], 
	[6, 7, 3, 0], 
	[4, 5, 9, 1]] 
	
result = [[0, 0, 0, 0], 
		[0, 0, 0, 0], 
		[0, 0, 0, 0]] 

# iterating by row of A 
for i in range(len(A)): 

	# iterating by coloum by B 
	for j in range(len(B[0])): 

		# iterating by rows of B 
		for k in range(len(B)): 
			result[i][j] += A[i][k] * B[k][j] 

for r in result: 
	print(r) 


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


Method 2: Matrix Multiplication Using Nested List. We use zip in Python.



In [2]:
# Program to multiply two matrices using list comprehension 

# take a 3x3 matrix 
A = [[12, 7, 3], 
	[4, 5, 6], 
	[7, 8, 9]] 

# take a 3x4 matrix 
B = [[5, 8, 1, 2], 
	[6, 7, 3, 0], 
	[4, 5, 9, 1]] 

# result will be 3x4 
result = [[sum(a * b for a, b in zip(A_row, B_col)) 
						for B_col in zip(*B)] 
								for A_row in A] 

for r in result: 
	print(r) 


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


Method 3: Matrix Multiplication (Vectorized implementation).

In [3]:
# Program to multiply two matrices (vectorized implementation) 

# Program to multiply two matrices (vectorized implementation) 
import numpy as np 
# take a 3x3 matrix 
A = [[12, 7, 3], 
	[4, 5, 6], 
	[7, 8, 9]] 

# take a 3x4 matrix 
B = [[5, 8, 1, 2], 
	[6, 7, 3, 0], 
	[4, 5, 9, 1]] 

# result will be 3x4 

result= [[0,0,0,0], 
		[0,0,0,0], 
		[0,0,0,0]] 

result = np.dot(A,B) 

for r in result: 
	print(r) 


[114 160  60  27]
[74 97 73 14]
[119 157 112  23]
