### **Transpose a matrix in Single line in Python**

1. Using Nested List Comprehension: 

Nested list comprehension are used to iterate through each element in the matrix.In the given example ,we iterate through each element of matrix (m) in column major manner and assign the result to rez matrix which is the transpose of m.






In [7]:
m = [[1,2],[3,4],[5,6]] 
for row in m : 
	print(row) 
rez = [[m[j][i] for j in range(len(m))] for i in range(len(m[0]))] 
print("\n") 
for row in rez: 
	print(row) 


[1, 2]
[3, 4]
[5, 6]


[1, 3, 5]
[2, 4, 6]


2. Using zip:

 Zip returns an iterator of tuples, where the i-th tuple contains the i-th element from each of the argument sequences or iterables. In this example we unzip our array using * and then zip it to get the transpose.

In [8]:
matrix=[(1,2,3),(4,5,6),(7,8,9),(10,11,12)] 
for row in matrix: 
	print(row) 
print("\n") 
t_matrix = zip(*matrix) 
for row in t_matrix: 
	print(row) 


(1, 2, 3)
(4, 5, 6)
(7, 8, 9)
(10, 11, 12)


(1, 4, 7, 10)
(2, 5, 8, 11)
(3, 6, 9, 12)


3. Using numpy: NumPy is a general-purpose array-processing package designed to efficiently manipulate large multi-dimensional arrays. The transpose method returns a transposed view of the passed multi-dimensional matrix.

In [9]:
# You need to install numpy in order to import it 
# Numpy transpose returns similar result when 
# applied on 1D matrix 
import numpy 
matrix=[[1,2,3],[4,5,6]] 
print(matrix) 
print("\n") 
print(numpy.transpose(matrix)) 


[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


simply using “.T” after the variable

In [10]:
# You need to install numpy in order to import it 
import numpy as np 
matrix = np.array([[1,2,3],[4,5,6]]) 
print(matrix) 
print("\n") 
print(matrix.T) 


[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]
